// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Date;

namespace Shop.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20210601222541_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Date.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descCategory");

                    b.Property<string>("nameCategory");

                    b.HasKey("id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("Shop.Date.Models.Knife", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("available");

                    b.Property<int>("categoryID");

                    b.Property<string>("imgKnife");

                    b.Property<bool>("isFavorite");

                    b.Property<string>("longDisc");

                    b.Property<string>("nameKnife");

                    b.Property<int>("priceKnife");

                    b.Property<string>("shortDisc");

                    b.Property<string>("steal");

                    b.HasKey("id");

                    b.HasIndex("categoryID");

                    b.ToTable("knife");
                });

            modelBuilder.Entity("Shop.Date.Models.Knife", b =>
                {
                    b.HasOne("Shop.Date.Models.Category", "Category")
                        .WithMany("knivesList")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
